### ISSUE TITLE
Moving files does not work for non-URL safe paths or filenames

### ISSUE THREAD

**Issue by judgej** [academe/flysystem-azure-file-storage#2]
Issue from PR #1 (@maetthu sorry, I had issues disabled for some reason)

Copying/Renaming files containing spaces, unicode characters or other non-url-safe characters results in following error:

`Fail: Code: 403 Value: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. details (if any):  AuthenticationFailedServer failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. [...] The MAC signature found in the HTTP request 'XXX' is not the same as any computed signature. `

Uploading files to root folder w/o path prefix results in a similar error.

**Comment by judgej** [comment]
I wonder if this encoding is entirely correct. The URL for a file at `foo bar/test 2.txt` looks like this:

    https://mystorageaccount.file.core.windows.net/mystoragename/foo%20bar%2Ftest%202.txt

I suspect the URL should look more like:

    https://mystorageaccount.file.core.windows.net/mystoragename/foo%20bar/test%202.txt

In other words, the parts of the path are encoded, but not the path separators.

However, as I discovered with some REST APIs years ago, you cannot encode a `/` as `%2F` in the path part of a URL, and not have it interpreted by the server as a `/`. I never did work out whether this was a part of the W3C standard, or just an implementation thing.

For example, https://www.reddit.com/r%2FPHPhelp%2F and https://www.reddit.com/r/PHPhelp/ I *think* are the same URL, but I'm not entirely sure.

**Comment by judgej** [comment]
Apache has an ALLOW_ENCODED_SLASHES directive that changes the way it interprets encoded slashes received in a URL in a server request. Based on other confusions around encoded slashes in paths, it seems taht interpretation is up to the server. To my mind, we must not leave the interpretation up to what Azure happens to use today, so we must be explicit about it. The parts of the path must be encoded, but the directory separators must not.

**Comment by maetthu** [comment]
I agree, I couldn't find a definitive answer in an RFC and it looks like it comes down to implementation whether it's treated as the same or not. Azure seems to accept both, but I guess it's better to leave / as is, indeed.

**Comment by judgej** [comment]
Okay, working on that now.

**Comment by maetthu** [comment]
Re: spaces. I think the problem just was my first try fixing the unicode-issue using urlencode, which is using + instead of %20 for encoding spaces, which broke those filenames. I didn't try spaces by itself, so if this did work beforehand I'm sorry for the confusion.

**Comment by maetthu** [comment]
thx for the fix :slightly_smiling_face:

**Comment by judgej** [comment]
Thank you for the PR :-) It was a problem I was yet to hit, but would have almost certainly kicked me where it hurts in the near future, in production.
